//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTbl
    {
        public string BlogTitle { get; set; }
        public string BlogText { get; set; }
        public string BlogUrl { get; set; }
        public int BlodId { get; set; }
    }
}
