//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateTbl
    {
        public int CertificateId { get; set; }
        public string CertificateName { get; set; }
        public string CertificateTitle { get; set; }
        public string CertificateDescription { get; set; }
    }
}
