//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactTable
    {
        public int ContactId { get; set; }
        public string ContactTitle { get; set; }
        public string ContactDescription { get; set; }
        public int ContactPhone { get; set; }
        public string ContactMail { get; set; }
        public string ConactAddress { get; set; }
    }
}
