//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPortofioEntities4 : DbContext
    {
        public DbPortofioEntities4()
            : base("name=DbPortofioEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbilityTbl> AbilityTbl { get; set; }
        public virtual DbSet<BlogTbl> BlogTbl { get; set; }
        public virtual DbSet<CertificateTbl> CertificateTbl { get; set; }
        public virtual DbSet<ContactTable> ContactTable { get; set; }
        public virtual DbSet<ProfileTbl> ProfileTbl { get; set; }
    }
}
